apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-container-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-container-demo
  template:
    metadata:
      labels:
        app: multi-container-demo
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80
          volumeMounts:
            - name: shared-logs
              mountPath: /var/log/nginx

        - name: fluent-bit-sidecar
          image: fluent/fluent-bit:latest
          volumeMounts:
            - name: shared-logs
              mountPath: /var/log/nginx
          args:
            - -i
            - tail
            - -p
            - path=/var/log/nginx/access.log
            - -o
            - stdout

      volumes:
        - name: shared-logs
          emptyDir: {}
